### PR TITLE
Return city name when quering all available hotels with cityId

### PR DESCRIPTION
**Pull request by tbergq**

### CODE REVIEW

**Comment by tbergq** [comment]
@mrtnzlml please review

**Comment by tbergq** [comment]
Is there a way to use either or? in case it is, maybe we should integrate that? It doesn't really make sense to send both. 

say you send coordinats for barcelona and cityid for prague, what should happen?

**Comment by mrtnzlml** [comment]
You actually described my concern. I was thinking about throwing an error in this case instead of allowing it because it really doesn't make any sense.

**Comment by tbergq** [comment]
I created an issue

#110

**Pull request merged**
