### PR TITLE
Add passenger full name field

### PR DESCRIPTION
**Pull request by tbergq**

### CODE REVIEW

**Comment by michalsanger** [comment]
No tests? :-(

We did it little bit more robust here:
https://github.com/kiwicom/graphql/blob/e51d03d37198ae85bc2edf98d0397d79e99d59aa/src/identity/types/outputs/Identity.js#L42-L52

**Comment by mrtnzlml** [comment]
What do you want to test here? However, it's true that the `Identity` implementation is way more robust so maybe can you please reuse this logic @tbergq?

**Comment by michalsanger** [comment]
As I see on the web, both fields are required, but it's simple one line to handle edge cases so why not..

I'd add the field into some passengers query and be happy it's resolved :-)

**Comment by tbergq** [comment]
Sure, I am on it, also just to point out, your implementation does not handel firstname or lastname undefined

**Comment by mrtnzlml** [comment]
@tbergq Please fix this simple one line in `Identity` as well... :)

**Pull request merged**
