### PR TITLE
Location tests refactoring

### PR DESCRIPTION
**Pull request by michalsanger**
Merge after #18 

There were some untestable lines because Dataloader throws it's own exception when returned value is Error. 

There is more refactoring to be done, see #17

### CODE REVIEW

**Comment by mrtnzlml** [comment]
> There were some untestable lines because Dataloader throws it's own exception when returned value is Error.

I don't really understand what was the problem, but there is also optimistic data loader if you want to work with errors returned in batch loads.

**Comment by michalsanger** [comment]
The problem is when the return type of batchLoad function is like this `Promise<Array<Location[] | Error>>` then Flow force you to have this to handle the `Error` after calling `dataloader.load(...)`:
```js
if (possibleValues instanceof Error) {
  throw possibleValues;
}
```

But this case never happen. If the batchLoad returns `Error` dataloader rejects the promise and with `async/await` the `Error` is thrown. Those untested lines in `yarn test-ci` pissed me so much I created this PR :-) Plus I added tests for the new `location` query.

**Comment by mrtnzlml** [comment]
> Those untested lines in yarn test-ci pissed me so much I created this PR...

I know you like to hear something clever from more clever people so here is one wisdom from Dan Abramov for you: https://twitter.com/dan_abramov/status/944939741094535168 😊

**Comment by michalsanger** [comment]
@mrtnzlml Thanks for the link. Please also give me name of medicine you are now using to handle your strong OCD

**Pull request merged**
