### PR TITLE
Dependencies: Upgrade graphql-iso-date

### LINKED ISSUE #171: DateTime type doesn't resolve dates correctly
It returns `null` for strings like `2018-12-24` but I would expect an exception or valid date object...

### PR DESCRIPTION
**Pull request by tbergq**
add test for WhitelabeledServices date time input

closes #171

### CODE REVIEW

**Comment by mrtnzlml** [comment]
@tbergq Oh, that was easy... :) Did you find a commit where they fixed this, please?

**Comment by tbergq** [comment]
I didn't look for it, but I upgraded, tested and it worked.

**Comment by mrtnzlml** [comment]
I thinks it's probably this one: https://github.com/excitement-engineer/graphql-iso-date/pull/76

**Comment by tbergq** [comment]
But I see now that it was fixed in v.3.4.0

**Comment by mrtnzlml** [comment]
@tbergq Good. Can you please help me to upgrade even other dependencies? (`yarn upgrade-interactive --latest`) It's quite important as you can see... :)

**Comment by tbergq** [comment]
yes, I can do that 🙂

**Pull request merged**
