### PR TITLE
Added check if hotels are returned from Logitravel API

### PR DESCRIPTION
**Pull request by dinodsaurus**

### CODE REVIEW

**Comment by dinodsaurus** [comment]
Hey @mrtnzlml I just realized that @michalsanger is on holidays this week so if you could take a look at this PR that would be great 🙏

**Comment by mrtnzlml** [comment]
@dinodsaurus Hi, one more question - @michalsanger convinced me a long time ago to merge this `dynamicPackage` namespace without tests because he promised to deliver them later. But he never did. Is it possible to do it any time soon?

**Comment by dinodsaurus** [comment]
yep definitely, I have taken over this project so I will dedicate some time in the next sprint for the tests 👍

**Comment by mrtnzlml** [comment]
Thanks. I am never going to merge PRs with _"I will do it later"_ comments again, I promise... 😊

Please, don't forget to verify that this change is deployed correctly. We had difficulties with inconsistent deployments for last few weeks. Let me know in case of any problems.

**Pull request merged**
