### PR TITLE
Add the quantity of checked baggage

### PR DESCRIPTION
**Pull request by kantord**

### CODE REVIEW

**Comment by tbergq** [comment]
It works for 99% of my test bookings, however bid 6776372 has one checked bag, but graphql says 0

**Comment by kantord** [comment]
Why :cry: :sob:

**Comment by kantord** [comment]
2018-07-10-130418_726x603_scrot

Probably this is the explanation

**Comment by kantord** [comment]
Closing because we have a different plan now, and we'll not need this exact modification. If you need it, feel free to re-open.

**Pull request closed without merging**
