### PR TITLE
Add hint to use GraphiQL app during development

### PR DESCRIPTION
**Pull request by jaroslav-kubicek**
Potentially useful info for newcomers to the project.

### CODE REVIEW

**Comment by mrtnzlml** [comment]
Related issue: https://github.com/kiwicom/graphql/issues/117 (for this we need to use GraphiQL from our private repo 😞)

**Comment by jaroslav-kubicek** [comment]
Desktop app has the ability to modify the HTTP headers, that was what triggered me initially to add this into readme 😎

**Comment by mrtnzlml** [comment]
> Desktop app has the ability to modify the HTTP headers, that was what triggered me initially to add this into readme 😎

So you need to use Postman to get the header value? Or what do you mean? We need to login first using username and password...

**Comment by jaroslav-kubicek** [comment]
you can execute mutation `login` to retrieve token

**Comment by michalsanger** [comment]
@mrtnzlml this graphiql app supports setting headers https://github.com/skevy/graphiql-app

**Comment by mrtnzlml** [comment]
> you can execute mutation login to retrieve token

Could you please add info on how to actually use it? If I remember correctly it's not that simple because you have to prefix the header value with `Token: ...` for example. 🙂 

Note: There is `DEV_API_TOKEN` in envs on BLKN to simplify this but nobody is probably using it...

**Pull request merged**
